
spring:
  security:
    oauth2:
      client:
        registration:
          Google:
            client-id: google-client-id
            client-name: google-client-name
          Facebook:
            client-id: facebook-client-id
            client-name: facebook-client-name
          Twitter:
            client-id: twitter-client-id
            client-name: twitter-client-name
          Github:
            client-id: 6c269169efeeacd7057a
            client-secret: 7cca7ce74155f0c886890bdd4d7701dce3abef6b
            